name: ninilab
favicon: null
layout_spectrum: 0.8547752660233527
typography_spectrum: 0.22695959685370326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4643206929322332
  lightness: 0.394289382500574
  saturation: 0.9378164091613144
  rhythmicContrast: 0.6239062738604844
purpose: []
